/*
 * Swagger Employee Service
 * A sample restful application generated using OpenApiGenerator(https://github.com/OpenAPITools/openapi-generator) and its Gradle plugin (https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/README.adoc)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.milan.openapi.employee.api;

import com.milan.openapi.employee.ApiException;
import com.milan.openapi.employee.model.Employee;
import com.milan.openapi.employee.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeesApi
 */
//@Ignore
public class EmployeesApiTest {

    private final EmployeesApi api = new EmployeesApi();

    
    /**
     * Create an employee
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEmployeeTest() throws ApiException {
        Employee employee = new Employee();
        employee.setFirstName("sampleFirstName");
        employee.setLastName("sampleLastName");
        employee.setMiddleName("");
        employee.setId(12);
        api.createEmployee(employee);

        // TODO: test validations
//        assertNotNull(response);
    }
    
    /**
     * Delete specific employee
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteEmployeetByIdTest() throws ApiException {
        String employeeId = "12";
        Employee response = api.deleteEmployeetById(employeeId);

        // TODO: test validations
        assertNotNull(response);
    }
    
    /**
     * List all employees
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listEmployeesTest() throws ApiException {
        Integer limit = null;
        List<Employee> response = api.listEmployees(limit);
        // TODO: test validations
        assertNotNull(response);
    }
    
    /**
     * Info for a specific employee
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showEmployeetByIdTest() throws ApiException {
        String employeeId = "0";
        Employee response = api.showEmployeetById(employeeId);

        // TODO: test validations
        assertNotNull(response);
    }
    
    /**
     * Update an employee
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateEmployeeTest() throws ApiException {
    	Employee employee = new Employee();
        employee.setFirstName("sampleFirstName");
        employee.setLastName("sampleLastName");
        employee.setMiddleName("");
        employee.setId(12);
        api.updateEmployee(employee);

        // TODO: test validations
    }
    
}
