server:
  port: 8082
  servlet: 
    contextPath: /employee-service
  http2: 
    enabled: true  
spring:   
  profiles:
  application: 
    name: employee-service
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    show-sql: true    
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  datasource: 
    platform: postgres
    url: jdbc:postgresql://localhost:5432/poc_db
    username: myuser
    password: start123
    driver-class-name: org.postgresql.Driver
    driverclass: org.postgresql.Driver
    initialization-mode: always
    hikari: 
     schema: reactive_poc
management: 
  security: 
    enabled: false
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /employee-service/health
      exposure:
        include: refresh, health
    
logging:
  level:
    root: INFO
    com.mastercard.dxp.es: INFO
    org.springframework.web: INFO
    
poolSize:
  minPoolSize: 5
  maxPoolSize: 11